### ISSUE TITLE
[Regression] max_size() does not take the allocator's max_size() into account

### ISSUE THREAD

**Issue by alexkaratarakis** [boostorg/circular_buffer#29]
Boost >=1.69 implementation of [`max_size()`](https://github.com/boostorg/circular_buffer/blob/boost-1.69.0/include/boost/circular_buffer/base.hpp#L790) calls [this](https://github.com/boostorg/circular_buffer/blob/boost-1.69.0/include/boost/circular_buffer/allocators.hpp#L37) function which does NOT take into account the maximum size of the allocator.

Boost <= 1.68 implementation of [`max_size()`](https://github.com/boostorg/circular_buffer/blob/boost-1.68.0/include/boost/circular_buffer/base.hpp#L790)  was calling [this](https://github.com/boostorg/container/blob/boost-1.68.0/include/boost/container/allocator_traits.hpp#L327) function from `boost::container` which does take into account the maximum size of the allocator.

The relevant commit is ca3d6678ee565c0adaf03d04afa080a94891a01e @glenfe 

As a result, when using a custom allocator with limited size `MY_MAX_SIZE`, previous calls to `max_size()` would return `MY_MAX_SIZE`, but they will now return `(std::numeric_limits<size_type>::max)() / sizeof(value_type)`

**Comment by glenfe** [comment]
I'll take care of it for Boost 1.72

**Comment by glenfe** [comment]
@alexkaratarakis 7be41ca8f9d94bf7d6f612f43be9d1e6a61348a1 should address this. We're almost ready to ship 1.71, so the earliest it will be released is 1.72.

**Comment by alexkaratarakis** [comment]
Thanks for the swift response and fix!
