### ISSUE TITLE
Fail to compile circular_buffer/test/common.ipp with C++20 since std::allocator::max_size is removed in C++20

### ISSUE THREAD

**Issue by yuxianch** [boostorg/circular_buffer#38]
circular_buffer/test/common.ipp is calling std::allocator::max_size, which is [removed in C++20](https://en.cppreference.com/w/cpp/memory/allocator/max_size).
https://github.com/boostorg/circular_buffer/blob/2b15dc6044ed5cec0f7422a073280d234e0b4e00/test/common.ipp#L250-L251

Need to make change to common.ipp so that it can conform to C++20 standard.

**Comment by glenfe** [comment]
Should be fixed in the next release.
